openapi: 3.0.0
info:
  title: inventory-service API
  version: 1.0.0
paths:
  /api/inventorys:
    get:
      summary: Retrieve items
      responses:
        '200':
          description: Successful response
    post:
      summary: Create new item
      responses:
        '201':
          description: Item created
